[system]
description = "Simplest system with both capability manager and scheduler, from unit_schedcomp.sh"

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}]
constructor = "booter"

[[components]]
name = "sched"
img  = "sched.deferrable_server"
#img  = "sched.sporadic_server"
#img  = "sched.sporadic_server_priority_aware"
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr"}, {srv = "capmgr", interface = "memmgr"}]
implements = [{interface = "sched"}, {interface = "init"}]
constructor = "booter"

[[components]]
name = "schedtest"
img  = "tests.threads"
deps = [{srv = "sched", interface = "init"}, {srv = "sched", interface = "sched"}, {srv = "capmgr", interface = "capmgr_create"}]
#params = [{key = "1024", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "512", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "256", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "128", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "64", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "32", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
params = [{key = "16", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
constructor = "booter"  

# To create test threads
# params = [{key = "1", value = "type,priority,period _us,budget_us,execution_us,block_us"}...


#params = [{key = "1024", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "512", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "256", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "128", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "64", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "32", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]
#params = [{key = "16", value = "0,4,200000,1,0,0"}, {key = "1", value = "3,3,200000,10000,0,200000"}]